// @generated by cucumber-viz settings UI
// Changes made through cucumber-viz.config.ts directly will be preserved, but user comments are lost on save.
import { defineConfig } from 'cucumber-viz/config';

export default defineConfig({
  featurePaths: [
    'examples/collection-review/subs/integration-tests/src/features/**/*.viz.feature',
  ],
  componentPaths: {},
  testCommand: 'npm --prefix examples/collection-review run test:cucumber -- "$(realpath "{file}")"',
  agentBackend: 'codex',
  reviewPeerBackend: 'opencode',
  claudeDefaultEffort: 'high',
  claudeIterationEffort: 'medium',
  workflowIterationExecuteVariant: 'default',
  checks: {
    profile: 'nodejs-react',
    overrides: {
      static: {
        executor: {
          kind: 'command',
          commands: [
            {
              name: 'worktree-dependencies',
              cmd: 'npm',
              args: ['run', 'worktree:prepare'],
            },
            {
              name: 'type-check',
              cmd: 'npm',
              args: ['run', 'type-check'],
            },
          ],
          parallel: false,
        },
      },
      regression: {
        executor: {
          kind: 'command',
          commands: [
            {
              name: 'vitest',
              cmd: 'npm',
              args: ['test'],
            },
          ],
          parallel: false,
          mutex: true,
        },
      },
    },
  },
  documentRetention: {
    enabled: false,
  },
  port: 4080,
});
