import { performance } from 'node:perf_hooks';
import { readProject } from '../../../dist/subs/analysis/subs/project/src/read-project.js';
import { parseDescription } from '../../../dist/subs/analysis/subs/descriptions/src/parse.js';
import { linkDescriptions } from '../../../dist/subs/analysis/subs/descriptions/src/link.js';
import { buildModel, deriveSourceAreas } from '../../../dist/subs/analysis/subs/model/src/index.js';
import { createDefaultTagRegistry } from '../../../dist/subs/analysis/subs/model/src/registry.js';
import { createSourceAnalysis } from '../../../dist/subs/analysis/subs/typescript/src/source-analysis.js';
import { evaluateAccesses } from '../../../dist/subs/analysis/src/evaluate-accesses.js';

const root = process.argv[2] ?? new URL('../../../examples/collection-review', import.meta.url).pathname;
const acquisition = { attempts: 1, maxFiles: 50000, maxApplicationFiles: 20000, maxFileBytes: 8 * 1024 * 1024, maxInputBytes: 256 * 1024 * 1024, maxApplicationBytes: 64 * 1024 * 1024, maxOwners: 1000, maxDepth: 64, deadlineMs: 30000 };
const source = { maxExports: 1000000, maxAccesses: 1000000, maxSelections: 1000000, maxForwardingDepth: 64, deadlineMs: 90000 };
const marks = [];
let last = performance.now();
const mark = (label) => { const now = performance.now(); marks.push([label, (now - last).toFixed(1)]); last = now; };
const registry = createDefaultTagRegistry();
const acquired = await readProject({ request: { cwd: root, scope: 'whole-project', configuration: 'discover' }, parse: parseDescription, limits: acquisition });
mark('acquire (root, config helper, inventory, reads)');
if (acquired.status !== 'acquired') { console.log(acquired); process.exit(1); }
const view = acquired.view;
const areas = [];
for (const module of view.inventory.modules) areas.push(...deriveSourceAreas(registry, module.id, module.areas.find(a => a.kind === 'ordinary').root, module.headerTags).value);
const analysis = await createSourceAnalysis({ view, inventory: view.inventory, areas, limits: source });
mark('compiler helper spawn + program creation');
const catalog = await analysis.catalog();
mark('catalog (exports/originals)');
const linked = linkDescriptions({ registry, inventory: view.inventory, catalog });
const model = buildModel(linked.modelInput);
mark('link + model');
const accesses = await analysis.accesses();
mark('accesses (imports interpretation)');
await analysis.dispose();
mark('compiler dispose');
const evaluation = evaluateAccesses(model.value, accesses.accesses, 100000);
mark('decide');
const seal = await view.seal();
mark('seal (re-validate captured inputs)');
await view.dispose();
console.log(root, '| files:', view.inventory.files.length, 'inputs:', view.inputs.length, 'originals:', catalog.originals.length, 'accesses:', accesses.accesses.length, 'denied:', evaluation.diagnostics.length, 'seal:', seal.status);
for (const [label, ms] of marks) console.log(ms.padStart(8), 'ms ', label);
