import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { AnalysisReport } from '../../subs/analysis/src/index.js';
import { assertReference, ownerId, sourcePath } from './linking-expectations.js';
import { analysisEvidence, recordObservation } from './observations.js';
import type { Assertions } from './runner.js';
import { clean } from './session-expectations.js';

export const referenceOwners = ['', 'integration-tests', 'workspace', 'workspace/catalog',
  'workspace/catalog/core', 'workspace/catalog/ui', 'workspace/contracts', 'workspace/reviews',
  'workspace/reviews/core', 'workspace/reviews/core/controller', 'workspace/reviews/core/tasks',
  'workspace/reviews/ui', 'workspace/reviews/ui/pure-ui', 'workspace/reviews/validation', 'workspace/shared-ui'];

export async function filesBelow(root: string, directory = ''): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(join(root, directory), { withFileTypes: true })) {
    if (['node_modules', 'dist', '.reference-work', '.git'].includes(entry.name)) continue;
    const path = directory ? `${directory}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...await filesBelow(root, path));
    else if (entry.isFile()) files.push(path);
  }
  return files.sort();
}

/** Expectations name authored source witnesses; no outcome is generated by the model. */
export async function assertBaseline(report: AnalysisReport, assertions: Assertions, root: string): Promise<void> {
  recordObservation('reference-baseline', analysisEvidence(report));
  clean(report, assertions);
  const snapshot = report.snapshot!;
  const { catalog, linked, inventory, accesses, results } = snapshot;
  if (!catalog || linked?.status !== 'valid') throw new Error('Baseline lacks catalog or valid contracts');
  assertions.equal('exact fifteen declared owners', inventory.modules.map(module => module.id), referenceOwners.map(ownerId));
  assertions.equal('expected whole baseline counts', report.summary, { complete: true, owners: 15,
    sourceFiles: 54, resources: 5, originals: 89, accesses: 294, allowed: 166, denied: 0,
    errors: 0, warnings: 2, coverageNotes: 0, external: 128 });
  assertions.equal('separate expected configuration warnings', report.warnings,
    ['vite.config.ts', 'vitest.config.ts'].map(file => ({ code: 'outside-module-source', entry: file, count: 1, files: [file] })));
  const disk = (await Promise.all(referenceOwners.map(owner => filesBelow(root, sourcePath(owner, '').replace(/\/$/, ''))))).flat().sort();
  assertions.equal('every owned implementation test and resource inventoried', inventory.files.map(file => file.path).sort(), disk);
  const unimportedResources = ['subs/integration-tests/src/features/collection-review.viz.feature', 'subs/workspace/src/index.html'];
  assertions.equal('all source and effective resource exports catalogued', catalog.files.map(file => [file.file, file.state]).sort(),
    disk.map(file => [file, unimportedResources.includes(file) ? 'incomplete' : 'complete']).sort());
  assertions.equal('resources without effective export descriptions are never source targets', accesses.filter(access =>
    access.target.kind === 'application' && unimportedResources.includes(access.target.origin.file)), []);
  assertReference({ input: { inventory }, catalog, linked }, assertions);
  assertions.equal('one evaluation per access without duplicates', results.map(result => result.accessId).sort(), accesses.map(access => access.id).sort());
  assertions.equal('unique occurrence identities', new Set(accesses.map(access => access.id)).size, accesses.length);
  for (const access of accesses) {
    const prefix = `${access.location.file}:${access.location.start}:${access.id}`;
    const result = results.find(result => result.accessId === access.id)!;
    assertions.equal(`${prefix}: no hidden coverage`, access.coverageIds, []);
    if (access.target.kind === 'application') {
      assertions.equal(`${prefix}: all selections resolved`, access.selections.map(selection => selection.status), access.selections.map(() => 'resolved'));
      assertions.equal(`${prefix}: selected originals or load checked`, result.decisions.map(decision => decision.status),
        Array.from({ length: Math.max(1, access.selections.length) }, () => 'allowed'));
      assertions.equal(`${prefix}: checked application`, result.outcome, 'checked');
    } else {
      assertions.equal(`${prefix}: proven external`, access.target.kind, 'external');
      if (access.target.kind !== 'external') throw new Error('Unresolved baseline access');
      assertions.ok(`${prefix}: compiler scope proof`, access.target.resolution === 'builtin' || !!access.target.resolvedFile);
      assertions.equal(`${prefix}: external is separate from application permission`, [result.outcome, result.decisions], ['external', []]);
    }
  }
  const selected = (file: string, binding: string, form?: string) => {
    const found = accesses.filter(access => access.importer.file === file && (!form || access.form === form)
      && access.selections.some(selection => selection.original?.binding === binding));
    assertions.equal(`${file}#${binding}: exact authored witness`, found.length, 1);
    return found[0]!;
  };
  for (const [binding, owner] of [['createCatalogRouter', 'workspace/catalog'], ['createCatalogTools', 'workspace/catalog'],
    ['createReviewsRouter', 'workspace/reviews'], ['createReviewsTools', 'workspace/reviews']] as const) {
    const access = selected('src/assembly.ts', binding);
    assertions.equal(`${binding}: root receives original factory`, access.selections[0].original?.owner, ownerId(owner));
    assertions.ok(`${binding}: actual relay path`, results.find(result => result.accessId === access.id)!.decisions[0].visibility?.paths.some(path => path.length >= 2));
  }
  const forwarded = selected('subs/workspace/src/client.ts', 'AppRouter');
  assertions.equal('R3 preserves assembly original through protocol alias', forwarded.selections[0].original,
    { kind: 'code', owner: 'collection-review', file: 'assembly.ts', binding: 'AppRouter' });
  assertions.equal('R3 retains the accessed forwarding source', forwarded.selections[0].forwarding.map(origin => origin.file), ['src/interfaces/protocol.ts']);
  const lazy = selected('subs/workspace/src/app.tsx', 'ReviewPanel', 'dynamic-import');
  assertions.equal('reference lazy callback selects only ReviewPanel', [lazy.selectionForm, lazy.selections.map(selection => selection.exportedName)], ['then-member', ['ReviewPanel']]);
  const query = selected('subs/workspace/src/tests/shell.test.tsx', 'ReviewPanel', 'import-type-query');
  assertions.equal('import-type query never loads a value', [query.runtimeLoad, query.selections[0].request], [false, 'type-only']);
  assertions.ok('configured alias is an application access', accesses.some(access => access.specifier?.startsWith('@features/') && access.target.kind === 'application'));
  const hook = accesses.find(access => access.importer.file === 'subs/integration-tests/src/steps/collection-review.steps.ts' && access.form === 'side-effect-import')!;
  assertions.ok('standalone testing module hook exists', hook);
  assertions.equal('hook has testing ordinary source and no invented binding', [hook.importer.area.kind, hook.importer.area.profile, hook.selections], ['ordinary', ['dispatch', 'testing'], []]);
  assertions.equal('distinct CSS resource bindings checked', new Set(accesses.flatMap(access => access.selections)
    .filter(selection => selection.original?.kind === 'resource').map(selection => selection.original?.owner + '/' + selection.original?.file)).size, 2);
  recordObservation('baseline-source-witnesses', { files: inventory.files.map(file => ({ path: file.path, owner: file.owner, area: file.area, kind: file.kind })),
    owners: inventory.modules.map(module => module.id), accesses,
    decisions: results.flatMap(result => result.decisions).map(decision => ({ status: decision.status, reason: decision.reason,
      original: decision.original?.id ?? null, importer: decision.question.importer, location: decision.question.location })) });
}
