import { curveCatmullRom, line as d3Line } from 'd3-shape';
import { placeNodes } from './node-placement.js';
import { LAYOUT } from './geometry.js';
import type { Box, Point, LayoutGraphInput, LayoutOptions, LayoutResult } from './interfaces/layout.js';

interface PlacedNode { readonly box: Box; readonly depth: number }
interface Geometry { readonly nodes: readonly PlacedNode[]; readonly left: number; readonly right: number }

type Interval = readonly [number, number];

function freeIntervals(boxes: readonly PlacedNode[], lo: number, hi: number, pad: number): Interval[] {
  const blocked = boxes
    .map((node): Interval => [node.box.x - pad, node.box.x + node.box.width + pad])
    .sort((a, b) => a[0] - b[0]);
  const free: Interval[] = [];
  let cursor = lo;
  for (const [start, end] of blocked) {
    if (start > cursor) {
      free.push([cursor, Math.min(start, hi)]);
    }
    cursor = Math.max(cursor, end);
  }
  if (cursor < hi) {
    free.push([cursor, hi]);
  }
  return free.filter(([start, end]) => end - start > 4);
}

function intersect(a: readonly Interval[], b: readonly Interval[]): Interval[] {
  const out: Interval[] = [];
  for (const [aStart, aEnd] of a) {
    for (const [bStart, bEnd] of b) {
      const start = Math.max(aStart, bStart);
      const end = Math.min(aEnd, bEnd);
      if (end - start > 4) {
        out.push([start, end]);
      }
    }
  }
  return out;
}

/**
 * The x a node's chords drop through: as close to the node's centre as
 * possible while clearing every box on every level below it, so that no chord
 * is ever drawn over a node box (§3.6, routing).
 */
function corridorX(geometry: Geometry, node: PlacedNode): number {
  const center = node.box.x + node.box.width / 2;
  const below = geometry.nodes.filter((other) => other.depth > node.depth);
  if (below.length === 0) {
    return center;
  }
  const lo = geometry.left - 40;
  const hi = geometry.right + 40;
  const depths = [...new Set(below.map((other) => other.depth))].sort((a, b) => a - b);
  let candidates: Interval[] = [[lo, hi]];
  for (const depth of depths) {
    candidates = intersect(
      candidates,
      freeIntervals(below.filter((other) => other.depth === depth), lo, hi, 14),
    );
  }
  if (candidates.length === 0) {
    return center;
  }
  const clamp = ([start, end]: Interval): number => Math.min(Math.max(center, start), end);
  const best = candidates.reduce((chosen, candidate) =>
    Math.abs(clamp(candidate) - center) < Math.abs(clamp(chosen) - center) ? candidate : chosen,
  );
  return clamp(best);
}

/** Sample the cubic segments generated by d3. Knots remain exact; the renderer
 * receives only neutral points, without a path string or library object.
 */
function smoothPoints(knots: readonly Point[]): Point[] {
  const points: Point[] = [];
  let current: Point = { x: 0, y: 0 };
  const context = {
    moveTo(x: number, y: number): void { current = { x, y }; points.push(current); },
    lineTo(x: number, y: number): void { current = { x, y }; points.push(current); },
    closePath(): void {},
    bezierCurveTo(x1: number, y1: number, x2: number, y2: number, x: number, y: number): void {
      const start = current;
      // Sub-pixel chord error at teaching-diagram sizes, including steep drops.
      for (let step = 1; step <= 48; step += 1) {
        const t = step / 48;
        const u = 1 - t;
        points.push({ x: u*u*u*start.x + 3*u*u*t*x1 + 3*u*t*t*x2 + t*t*t*x,
          y: u*u*u*start.y + 3*u*u*t*y1 + 3*u*t*t*y2 + t*t*t*y });
      }
      current = { x, y };
    },
  };
  d3Line<Point>().x(point => point.x).y(point => point.y)
    .curve(curveCatmullRom.alpha(0.5)).context(context as CanvasRenderingContext2D)(knots);
  return points;
}

/** Place curved connections beneath measured boxes. A lane is a nonnegative
 * endpoint clearance; order breaks equal-span ties without interpreting keys.
 */
export function placeChords(input: LayoutGraphInput, options: LayoutOptions): LayoutResult {
  if (options.orientation === 'horizontal') {
    const placed = placeChords({
      nodes: input.nodes.map(node => ({ ...node, width: node.height, height: node.width })),
      edges: input.edges,
    }, { ...options, orientation: 'vertical', gapX: options.gapY, gapY: options.gapX });
    return {
      nodes: placed.nodes.map(node => ({ key: node.key, box: {
        x: node.box.y, y: node.box.x, width: node.box.height, height: node.box.width,
      } })),
      edges: placed.edges.map(edge => ({ key: edge.key,
        points: edge.points.map(point => ({ x: point.y, y: point.x })),
      })),
      bounds: { x: placed.bounds.y, y: placed.bounds.x,
        width: placed.bounds.height, height: placed.bounds.width },
    };
  }
  const placed = placeNodes(input, options);
  const inputs = new Map(input.nodes.map(node => [node.key, node]));
  const depthOf = (key: string): number => {
    const node = inputs.get(key);
    if (node === undefined) throw new Error(`Unknown node "${key}".`);
    return node.parent === null ? 0 : depthOf(node.parent) + 1;
  };
  const byKey = new Map(placed.nodes.map(node => [node.key, { box: node.box, depth: depthOf(node.key) }]));
  const geometry: Geometry = { nodes: [...byKey.values()], left: placed.bounds.x, right: placed.bounds.x + placed.bounds.width };
  const nodeOf = (key: string): PlacedNode => {
    const node = byKey.get(key);
    if (node === undefined) throw new Error(`Unknown chord endpoint "${key}".`);
    return node;
  };
  const ordered = [...input.edges].sort((a, b) => {
    const spanA = Math.abs(corridorX(geometry, nodeOf(a.from)) - corridorX(geometry, nodeOf(a.to)));
    const spanB = Math.abs(corridorX(geometry, nodeOf(b.from)) - corridorX(geometry, nodeOf(b.to)));
    return spanA - spanB || a.order - b.order;
  });
  const attachments = new Map<string, number>();
  const perNode = new Map<string, string[]>();
  for (const edge of ordered) {
    for (const [key, end] of [[edge.from, 'from'], [edge.to, 'to']] as const) {
      const list = perNode.get(key) ?? [];
      list.push(`${edge.key}:${end}`);
      perNode.set(key, list);
    }
  }
  for (const [key, ends] of perNode) {
    const base = corridorX(geometry, nodeOf(key));
    ends.forEach((end, index) => attachments.set(end, base + (index - (ends.length - 1) / 2) * LAYOUT.chord.endpointSpread));
  }
  const rowTop = placed.bounds.y + placed.bounds.height + LAYOUT.chord.topGap;
  const edges = ordered.map((edge, row) => {
    const from = nodeOf(edge.from).box;
    const to = nodeOf(edge.to).box;
    const x1 = attachments.get(`${edge.key}:from`) ?? from.x + from.width / 2;
    const x2 = attachments.get(`${edge.key}:to`) ?? to.x + to.width / 2;
    const rowY = rowTop + row * LAYOUT.chord.rowHeight;
    return { key: edge.key, points: smoothPoints([
      { x: x1, y: from.y + from.height }, { x: x1, y: rowY - 12 },
      { x: (x1 + x2) / 2, y: rowY }, { x: x2, y: rowY - 12 },
      { x: x2, y: to.y + to.height + edge.lane },
    ]) };
  });
  return { ...placed, edges };
}
