import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { createPiAgent, piReadiness } from './runtime/ramify-agent/subs/harness/subs/agent/subs/pi/src/pi-agent.ts';
import { engineerEquipment } from './runtime/ramify-agent/subs/harness/src/work/engineer-equipment.ts';
import { RamifyCli } from './runtime/ramify-agent/subs/harness/subs/evidence/src/ramify-cli.ts';
import { loadArchitectIndex } from './runtime/ramify-agent/subs/harness/subs/evidence/src/views.ts';
import { ObservationLog } from './runtime/ramify-agent/subs/harness/src/run/observations.ts';
import { contractJsonSchema, validateContract } from './runtime/ramify-agent/subs/harness/src/contracts/submission.ts';

const root = '/tmp/ramify-contract-replay-20260926';
const original = '/tmp/ramify-sed-gpt6sol-reuse-20260926';
const job = join(original, 'plans/self-explaining-denials/.harness/jobs/20260926T052417Z-21d928');
const arm = process.argv[2];
if (!['baseline', 'improved'].includes(arm!)) throw new Error('Choose baseline or improved');
const projectRoot = join(root, arm!, 'project');
const records = join(root, arm!, 'records');
const json = async (path: string) => JSON.parse(await readFile(path, 'utf8'));
const assignment = await json(join(job, 'work-items/wi-001/iterations/02/assignment.json'));
const policy = (await json(join(job, 'job.json'))).policy;
const first = JSON.parse((await readFile(join(job, 'transcripts/ses-0006.jsonl'), 'utf8')).split('\n')[0]!);
const remap = (value: string) => value.replaceAll(original, projectRoot);
const sha = (value: string) => createHash('sha256').update(value).digest('hex');
let systemPrompt = remap(await readFile(join(job, 'blobs', first.systemPrompt.hash), 'utf8'));
const prompt = remap(await readFile(join(job, 'blobs', first.prompt.hash), 'utf8'));
if (arm === 'improved') systemPrompt += '\n\n' + await readFile(join(root, 'prompt-addition.md'), 'utf8');
await writeFile(join(records, 'system.md'), systemPrompt);
await writeFile(join(records, 'brief.md'), prompt);
const model = 'openai-codex/gpt-6-sol:medium';
const readiness = await piReadiness({ model });
console.log(JSON.stringify({ arm, readiness }));
if (!readiness.ready) process.exit(2);

const ramify = new RamifyCli({
  executable: '/tmp/ramify-harness-sed-fix-20260925/ramify-agent/node_modules/.bin/ramify',
  endpointDirectory: join(records, 'endpoint'),
});
const events: any[] = [];
let session: ReturnType<ReturnType<typeof createPiAgent>['startSession']> | undefined;
let equipment: ReturnType<ReturnType<typeof engineerEquipment>['equip']> | undefined;
let timer: NodeJS.Timeout | undefined;
let submitted: unknown = null;
let rejected = 0;
let timedOut = false;
try {
  for (const from of ['subs/analysis', 'subs/cli']) {
    const result = await ramify.materialize(projectRoot, from);
    await writeFile(join(records, `materialize-${from.split('/').at(-1)}.json`), JSON.stringify(result, null, 2));
    if (!result.ok) throw new Error(result.message);
  }
  let index = await loadArchitectIndex(projectRoot);
  const refresh = async () => {
    const result = await ramify.materialize(projectRoot);
    if (!result.ok) throw new Error(result.message);
    return index = await loadArchitectIndex(projectRoot);
  };
  const commands = JSON.parse(remap(JSON.stringify(policy.commands)));
  const observations = await ObservationLog.open(join(records, 'observations.jsonl'));
  const callIds = new Map<string, string>();
  const scope = assignment.scope.resolved;
  const guarded = {
    revision: assignment.scope.revision,
    roots: scope.roots.map(remap), files: scope.files.map(remap),
    denied: assignment.guarded.map((entry: any) => join(projectRoot, entry.path)),
  };
  const supplied = engineerEquipment({
    projectRoot, ramify, commands, bounds: policy.limits, refresh, index: () => index,
    guarded, scopeRevision: assignment.scope.revision, tests: assignment.gate.tests,
    outputPath: (kind, invocation, number) => join(records, kind, `${number}.log`),
    commandTimeoutMs: policy.limits.commandTimeoutMs,
  });
  equipment = supplied.equip({ invocation: arm!, observations, callId: tool => callIds.get(tool) ?? '', reminders: () => [] });
  const manifest = {
    arm, originalInvocation: 'inv-0008', base: '1803db6b72ea194730ad1a87d6cba459b35622e1',
    harnessSource: 'c4af2a4ee7d14f58391e72a334dc0d38ad2b557b', model,
    systemHash: sha(systemPrompt), briefHash: sha(prompt), scope: guarded,
    context: policy.context['contract-engineer'], tests: assignment.gate.tests,
    maxMs: 900000,
    limitations: [
      'Fresh isolated session, as in original; no deterministic model seed.',
      'Generated API and architect views rebuilt at baseline; original generated bytes were not archived.',
      'Harness source extracted from committed trial checkout; dependencies reused from trial installation.',
      'Absolute roots remapped; dependencies shared by symlink.',
      'This probe records a submission and stops; it does not register, commit, or run the contract checkpoint.',
      '15 minute outer bound replaces original 60 minute bound; materialization excluded from elapsedMs.',
    ],
  };
  await writeFile(join(records, 'manifest.json'), JSON.stringify(manifest, null, 2));
  await mkdir(join(records, 'session'), { recursive: true });
  const started = Date.now();
  session = createPiAgent({ model }).startSession({
    role: 'contract-engineer', scope: { workingDirectory: projectRoot }, systemPrompt, prompt,
    session: { mode: 'fresh' }, context: policy.context['contract-engineer'],
    builtinTools: equipment.builtinTools!, tools: equipment.tools!,
    guard: equipment.guard, afterMutation: equipment.afterMutation,
    sessionDirectory: join(records, 'session'),
    submission: {
      name: 'submit_contract_result',
      description: 'End your turn with the result of this contract iteration. The harness validates it; an invalid submission is returned with every error and its path, and a valid one ends this invocation.',
      inputSchema: contractJsonSchema,
      accept: async input => {
        const result = await validateContract(input, {
          index, consumer: 'ramify/cli', exists: path => stat(join(projectRoot, path)).then(s => s.isFile(), () => false),
        });
        if (!result.ok) { rejected++; return { accepted: false, text: JSON.stringify(result.errors) }; }
        submitted = input;
        await writeFile(join(records, 'submission.json'), JSON.stringify(input, null, 2));
        return { accepted: true };
      },
    },
    onEvent: event => {
      events.push(event);
      appendFileSync(join(records, 'events.jsonl'), JSON.stringify(event) + '\n');
      if (event.type === 'tool-started') {
        callIds.set(event.tool, event.callId);
        console.log(JSON.stringify({ arm, tool: event.tool, path: (event.input as any)?.path }));
      }
    },
  });
  timer = setTimeout(() => { timedOut = true; void session?.stop(); }, 900000);
  const outcome = await session.outcome;
  clearTimeout(timer);
  await equipment.settle?.();
  await session.settled();
  const usage = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 };
  const messages = events.filter(e => e.type === 'message' && e.role === 'assistant');
  for (const message of messages) for (const key of Object.keys(usage)) usage[key] += message.usage?.[key] ?? 0;
  const status = execFileSync('git', ['status', '--short'], { cwd: projectRoot, encoding: 'utf8' });
  const diff = execFileSync('git', ['diff', '--binary', 'HEAD'], { cwd: projectRoot, encoding: 'utf8' });
  await writeFile(join(records, 'tracked.diff'), diff);
  const report = { arm, elapsedMs: Date.now() - started, outcome, actualStart: session.start, ref: session.ref,
    submitted, rejected, timedOut, turns: messages.length, usage, status };
  await writeFile(join(records, 'result.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify({ arm, ended: outcome.kind, turns: messages.length, usage, status }));
} finally {
  clearTimeout(timer);
  await equipment?.settle?.();
  await session?.stop();
  await ramify.stopDaemon();
}
