import type { Destination, ModuleId, OriginalId } from '../subs/model/src/interfaces/model.js';
import type { ArchitectDependencies, ArchitectModuleFacts, ArchitectSymbol, ArchitectTestRecord, ArchitectViewFile,
  ArchitectViewProjection, RenderedArchitectView } from './interfaces/architect-view.js';
import type { DependencyBoundaryFact, DependencyDiagramFacts, TestReferenceFacts } from './interfaces/dependency-diagram.js';
import type { ArchitectMeasurements, ModuleMeasurement } from './interfaces/measurements.js';
import { byteOrder } from './modularity-context.js';

/**
 * Pure rendering of one architect projection and the dependency facts of its
 * revision into the exact files of docs/architecture/architect-view.spec.md.
 * It reads no compiler, filesystem or session state: the same input always
 * gives the same bytes, with no timestamp, host path or process value. Every
 * text field and list of a record is bounded here or by the projection's
 * limits, so a record's length does not grow with the project.
 */

const bounds = { purposeBytes: 600, consumers: 12, names: 4, headline: 8, exercises: 12 } as const;

/** The instruction block the view's `README.md` opens with, from the specification's agent instructions. */
export const architectInstructions = [
  'This directory is generated by `ramify materialize --view architect`.',
  'It is gitignored and never edited or imported.',
  '',
  'Architecture questions are searched here, not in the source:',
  "  rg -n -i '<terms>' .ramify-architect/",
  'Every hit names its module and role: exposed, internal, or a test title.',
  "A test record's exercises names the symbols its test file calls.",
  'For one module, read <module>/module.json, behavior.jsonl and tests.jsonl.',
  'The map below lists every module with its purpose and headline symbols.',
  '',
  "Whether module X may import a symbol is answered by X's own",
  'src/.ramify/ view, not by this directory.',
  'If _meta.json records coverage or unknownShapes, absence is not proof.',
  'Refresh a stale view with `ramify materialize --view architect`.',
].join('\n');

type UnitClass = DependencyBoundaryFact['classification'];
interface PairCounts { behavioral: number; nonBehavioral: number; unknown: number }
/** The (consumer module, original) units of the dependency facts, and their counts per module pair. */
interface Use {
  /** By original identity: each consumer module and its unit's class. */
  readonly consumers: ReadonlyMap<string, ReadonlyMap<ModuleId, UnitClass>>;
  /** By consumer module, then original owner. */
  readonly uses: ReadonlyMap<ModuleId, ReadonlyMap<ModuleId, PairCounts>>;
  /** By original owner, then consumer module. */
  readonly usedBy: ReadonlyMap<ModuleId, ReadonlyMap<ModuleId, PairCounts>>;
}

const identity = (original: OriginalId): string => JSON.stringify([original.owner, original.file, original.binding, original.kind]);

/**
 * Units grouped from the boundaries by consumer module and original identity,
 * with the dependency diagram's precedence: behavioral evidence settles a unit,
 * otherwise any unknown boundary leaves it unknown, otherwise it is
 * non-behavioral.
 */
function useOf(facts: DependencyDiagramFacts): Use {
  const units = new Map<string, { consumer: ModuleId; owner: ModuleId; original: string; classes: Set<UnitClass> }>();
  for (const boundary of facts.boundaries) {
    const original = identity(boundary.original);
    const key = JSON.stringify([boundary.consumer, original]);
    const unit = units.get(key) ?? { consumer: boundary.consumer, owner: boundary.originalOwner, original, classes: new Set() };
    unit.classes.add(boundary.classification);
    units.set(key, unit);
  }
  const consumers = new Map<string, Map<ModuleId, UnitClass>>();
  const uses = new Map<ModuleId, Map<ModuleId, PairCounts>>(), usedBy = new Map<ModuleId, Map<ModuleId, PairCounts>>();
  const count = (index: Map<ModuleId, Map<ModuleId, PairCounts>>, from: ModuleId, to: ModuleId, unitClass: UnitClass) => {
    const pairs = index.get(from) ?? new Map<ModuleId, PairCounts>();
    const counts = pairs.get(to) ?? { behavioral: 0, nonBehavioral: 0, unknown: 0 };
    if (unitClass === 'behavioral') counts.behavioral++;
    else if (unitClass === 'unknown') counts.unknown++;
    else counts.nonBehavioral++;
    pairs.set(to, counts);
    index.set(from, pairs);
  };
  for (const unit of units.values()) {
    const unitClass: UnitClass = unit.classes.has('behavioral') ? 'behavioral' : unit.classes.has('unknown') ? 'unknown' : 'non-behavioral';
    const byConsumer = consumers.get(unit.original) ?? new Map<ModuleId, UnitClass>();
    byConsumer.set(unit.consumer, unitClass);
    consumers.set(unit.original, byConsumer);
    count(uses, unit.consumer, unit.owner, unitClass);
    count(usedBy, unit.owner, unit.consumer, unitClass);
  }
  return { consumers, uses, usedBy };
}

const sorted = <T extends string>(values: Iterable<T>): T[] => [...values].sort(byteOrder);

/** `values` under `key`, at most `max` of them, with `<key>More` counting the rest. */
function bounded(record: Record<string, unknown>, key: string, values: readonly string[], max: number): void {
  record[key] = values.slice(0, max);
  if (values.length > max) record[`${key}More`] = values.length - max;
}

/** The longest prefix of `text` within `maxBytes` UTF-8 bytes that ends on a character boundary. */
function cutUtf8(text: string, maxBytes: number): { readonly text: string; readonly cut: boolean } {
  if (Buffer.byteLength(text, 'utf8') <= maxBytes) return { text, cut: false };
  let bytes = 0, end = 0;
  for (const character of text) {
    const size = Buffer.byteLength(character, 'utf8');
    if (bytes + size > maxBytes) break;
    bytes += size;
    end += character.length;
  }
  return { text: text.slice(0, end), cut: true };
}

interface SymbolRecord {
  readonly symbol: ArchitectSymbol;
  readonly line: string;
  /** Consumer modules in each list, including those beyond the bound. */
  readonly behavioral: number;
  readonly nonBehavioral: number;
}

/**
 * One `behavior.jsonl` or `supporting.jsonl` line, keys in the specification's
 * order, optional fields omitted. `consumers` is null when dependencies are
 * unavailable. A supporting record carries `behavioral` only when a consumer's
 * use of it was classified behavioral, so that every consumer still appears in
 * exactly one list.
 */
function symbolRecord(symbol: ArchitectSymbol, consumers: ReadonlyMap<ModuleId, UnitClass> | null): SymbolRecord {
  const behavior = symbol.behavior !== null;
  const record: Record<string, unknown> = { module: symbol.module, name: symbol.name };
  if (symbol.binding !== null) record.binding = symbol.binding;
  if (symbol.exposureNames.length) bounded(record, 'as', sorted(symbol.exposureNames), bounds.names);
  record.role = symbol.role;
  if (behavior) record.shape = symbol.behavior;
  else {
    record.kind = symbol.kind;
    if (symbol.hasValue) record.value = true;
  }
  if (symbol.role === 'exposed') record.to = sorted<Destination>(symbol.destinations);
  if (symbol.tags.length) record.tags = sorted(symbol.tags);
  if (symbol.reexposed.length) record.reexposed = symbol.reexposed.map(({ by, to }) => ({ by, to: sorted<Destination>(to) }));
  const lists = { behavioral: [] as ModuleId[], nonBehavioral: [] as ModuleId[], unclassified: [] as ModuleId[] };
  if (consumers) {
    for (const [consumer, unitClass] of consumers) {
      (unitClass === 'behavioral' ? lists.behavioral : unitClass === 'unknown' ? lists.unclassified : lists.nonBehavioral).push(consumer);
    }
    if (behavior || lists.behavioral.length) bounded(record, 'behavioral', sorted(lists.behavioral), bounds.consumers);
    bounded(record, 'nonBehavioral', sorted(lists.nonBehavioral), bounds.consumers);
    if (lists.unclassified.length) bounded(record, 'unclassified', sorted(lists.unclassified), bounds.consumers);
  }
  const { detail } = symbol;
  if (detail.state === 'unavailable') record.detail = detail.reason;
  else {
    record.sig = detail.signature;
    if (detail.documentation !== undefined) record.doc = detail.documentation;
    if (detail.state === 'truncated') {
      const cut: string[] = [];
      if (detail.truncated.includes('signature') || detail.truncated.includes('overloads')) cut.push('sig');
      if (detail.truncated.includes('documentation')) cut.push('doc');
      if (cut.length) record.cut = cut;
    }
  }
  record.file = symbol.file;
  return { symbol, line: JSON.stringify(record), behavioral: lists.behavioral.length, nonBehavioral: lists.nonBehavioral.length };
}

const roleRank = (symbol: ArchitectSymbol): number => symbol.role === 'exposed' ? 0 : 1;
const byName = (a: SymbolRecord, b: SymbolRecord): number => byteOrder(a.symbol.name, b.symbol.name)
  || byteOrder(a.symbol.file, b.symbol.file) || byteOrder(identity(a.symbol.original), identity(b.symbol.original));
/** `behavior.jsonl`: role, then behavioral and non-behavioral consumer counts descending, then name. */
const behaviorOrder = (a: SymbolRecord, b: SymbolRecord): number => roleRank(a.symbol) - roleRank(b.symbol)
  || b.behavioral - a.behavioral || b.nonBehavioral - a.nonBehavioral || byName(a, b);
/** `supporting.jsonl`: role, then non-behavioral consumer count descending, then name. */
const supportingOrder = (a: SymbolRecord, b: SymbolRecord): number => roleRank(a.symbol) - roleRank(b.symbol)
  || b.nonBehavioral - a.nonBehavioral || byName(a, b);

/**
 * Each test file's `exercises` labels, `<owner>#<name>` with the name of the
 * original's own record, distinct and in byte order; an original with no
 * record is left out. `unclassified` is the file's count of unknown pairs.
 */
interface Exercises {
  readonly byFile: ReadonlyMap<string, readonly string[]>;
  readonly unclassified: ReadonlyMap<string, number>;
}

function exercisesOf(references: TestReferenceFacts, projection: ArchitectViewProjection): Exercises {
  const labels = new Map(projection.symbols.map(symbol => [identity(symbol.original), `${symbol.module}#${symbol.name}`]));
  const byFile = new Map<string, readonly string[]>(), unclassified = new Map<string, number>();
  for (const entry of references.files) {
    const found = entry.exercises.map(original => labels.get(identity(original))).filter(label => label !== undefined);
    byFile.set(entry.file, sorted(new Set(found)));
    unclassified.set(entry.file, entry.unclassified);
  }
  return { byFile, unclassified };
}

/**
 * One `tests.jsonl` line; a feature record without a `Feature:` title omits
 * `feature`. A suite record carries its file's `exercises` when test
 * references are measured, `[]` for a file without an entry.
 */
function testRecord(record: ArchitectTestRecord, exercises: Exercises | null): string {
  if (record.kind === 'suite') {
    const line: Record<string, unknown> = { module: record.module, file: record.file, suite: record.suite, tests: record.tests };
    if (exercises) bounded(line, 'exercises', exercises.byFile.get(record.file) ?? [], bounds.exercises);
    return JSON.stringify(line);
  }
  const line: Record<string, unknown> = { module: record.module, file: record.file };
  if (record.feature !== null) line.feature = record.feature;
  line.scenarios = record.scenarios;
  return JSON.stringify(line);
}

const jsonl = (lines: readonly string[]): string => lines.length ? `${lines.join('\n')}\n` : '\n';
const str = (value: string): string => JSON.stringify(value);
const inlineList = (values: readonly string[]): string => `[${values.map(str).join(', ')}]`;
const inlineObject = (entries: readonly (readonly [string, string | number | boolean])[]): string =>
  `{ ${entries.map(([key, value]) => `${str(key)}: ${typeof value === 'string' ? str(value) : String(value)}`).join(', ')} }`;

interface ModuleSummary {
  readonly facts: ArchitectModuleFacts;
  readonly behavior: readonly SymbolRecord[];
  readonly supporting: readonly SymbolRecord[];
  readonly tests: readonly ArchitectTestRecord[];
  readonly purpose: { readonly text: string; readonly cut: boolean } | null;
  readonly uses: readonly (readonly [ModuleId, PairCounts])[] | null;
  readonly usedBy: readonly (readonly [ModuleId, PairCounts])[] | null;
}

/** Module pairs with the most behavioral, then non-behavioral, then unknown units first, then by identifier. */
function pairs(index: ReadonlyMap<ModuleId, PairCounts> | undefined): (readonly [ModuleId, PairCounts])[] {
  return [...index ?? []].sort(([a, left], [b, right]) => right.behavioral - left.behavioral
    || right.nonBehavioral - left.nonBehavioral || right.unknown - left.unknown || byteOrder(a, b));
}

const symbolCounts = (summary: ModuleSummary) => ({
  exposed: summary.behavior.filter(record => record.symbol.role === 'exposed').length,
  internal: summary.behavior.filter(record => record.symbol.role === 'internal').length,
  supporting: summary.supporting.length,
  unknown: summary.behavior.filter(record => record.symbol.behavior === 'unknown').length,
});
const titleCount = (summary: ModuleSummary): number =>
  summary.tests.reduce((total, record) => total + (record.kind === 'suite' ? record.tests.length : record.scenarios.length), 0);

/**
 * `module.json`: two-space indentation and the specification's key order.
 * Lists of strings and small objects stay on one line, and `uses` and `usedBy`
 * hold one pair per line; both are absent when dependencies are unavailable.
 */
function moduleDocument(summary: ModuleSummary, revision: string, measurements: ArchitectMeasurements,
  measurement: ModuleMeasurement | undefined): string {
  const { facts } = summary;
  const field = (key: string, value: string): string => `  ${str(key)}: ${value}`;
  const purpose = summary.purpose === null || facts.purpose.state === 'missing'
    ? inlineObject([['state', 'missing']])
    : `{\n    "state": "present",\n    "path": ${str(facts.purpose.path)},\n    "text": ${str(summary.purpose.text)}${summary.purpose.cut ? ',\n    "cut": true' : ''}\n  }`;
  const pairList = (entries: readonly (readonly [ModuleId, PairCounts])[]): string => entries.length
    ? `[\n${entries.map(([module, counts]) => `    ${inlineObject([['module', module], ['behavioral', counts.behavioral],
      ['nonBehavioral', counts.nonBehavioral], ...counts.unknown ? [['unknown', counts.unknown] as const] : []])}`).join(',\n')}\n  ]`
    : '[]';
  const symbols = symbolCounts(summary);
  const metrics = measurements.state === 'unavailable'
    ? { state: 'unavailable', reason: measurements.reason }
    : { state: 'measured', views: measurements.views,
      contextSize: { exact: measurement!.exact, subtree: measurement!.subtree } };
  const fields = [
    field('schema', str('ramify.architect-module/1')),
    field('module', str(facts.module)),
    field('dir', str(facts.dir)),
    field('parent', facts.parent === null ? 'null' : str(facts.parent)),
    field('children', inlineList(facts.children)),
    field('tags', inlineList(sorted(facts.tags))),
    field('areas', inlineList(facts.areas)),
    field('purpose', purpose),
    field('docs', inlineList(facts.docs)),
    field('files', inlineObject([['own', facts.files.own], ['subtree', facts.files.subtree]])),
    field('symbols', inlineObject([['exposed', symbols.exposed], ['internal', symbols.internal], ['supporting', symbols.supporting],
      ['unknown', symbols.unknown]])),
    field('tests', inlineObject([['suites', summary.tests.length], ['titles', titleCount(summary)]])),
    ...summary.uses && summary.usedBy ? [field('uses', pairList(summary.uses)), field('usedBy', pairList(summary.usedBy))] : [],
    field('metrics', JSON.stringify(metrics)),
    field('revision', str(revision)),
  ];
  return `{\n${fields.join(',\n')}\n}\n`;
}

/**
 * `README.md`: the instruction block, the revision and input, then one map
 * entry per module in tree order, indented two spaces per level below the root.
 */
function readme(revision: string, projection: ArchitectViewProjection, summaries: readonly ModuleSummary[]): string {
  const depth = new Map<ModuleId, number>();
  const lines = ['```text', architectInstructions, '```', '', `Revision ${revision} · input ${projection.inputId}`, ''];
  for (const summary of summaries) {
    const { facts } = summary;
    const level = facts.parent === null ? 0 : (depth.get(facts.parent) ?? 0) + 1;
    depth.set(facts.module, level);
    const indent = '  '.repeat(level);
    const tags = facts.tags.length ? ` [${sorted(facts.tags).join(', ')}]` : '';
    const purpose = summary.purpose === null ? '(no README purpose)' : `${summary.purpose.text}${summary.purpose.cut ? '…' : ''}`;
    lines.push(`${indent}- **${facts.module}**${tags} — ${purpose}`);
    const symbols = symbolCounts(summary);
    const use = summary.uses && summary.usedBy ? `uses ${summary.uses.length} · used by ${summary.usedBy.length}` : 'uses ? · used by ?';
    lines.push(`${indent}  exposed ${symbols.exposed} · internal ${symbols.internal} · supporting ${symbols.supporting}`
      + ` · tests ${titleCount(summary)} · ${use}`);
    const headline = summary.behavior.filter(record => record.symbol.role === 'exposed').map(record => record.symbol.name);
    if (headline.length) {
      const rest = headline.length - bounds.headline;
      lines.push(`${indent}  headline: ${headline.slice(0, bounds.headline).join(', ')}${rest > 0 ? `, … +${rest}` : ''}`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/**
 * `_meta.json`: one line, the fixed fields, then each exceptional count only
 * when nonzero. `unclassifiedExercises` sums the unknown pairs of the files
 * that have a suite record.
 */
function metadata(revision: string, projection: ArchitectViewProjection, dependencies: ArchitectDependencies,
  exercises: Exercises | null, purposesCut: number, measurements: ArchitectMeasurements): string {
  const meta: Record<string, unknown> = { schema: 'ramify.architect-view/1', revision, input: projection.inputId,
    modules: projection.modules.length, dependencies: dependencies.state };
  if (dependencies.state === 'unavailable') meta.dependencyReason = dependencies.reason;
  meta.dependencyScope = 'production';
  meta.testReferences = exercises ? 'measured' : 'unavailable';
  meta.metrics = measurements.state;
  const { counts } = projection;
  const suiteFiles = new Set(projection.tests.filter(record => record.kind === 'suite').map(record => record.file));
  const unclassifiedExercises = [...exercises?.unclassified ?? []]
    .reduce((total, [file, count]) => total + (suiteFiles.has(file) ? count : 0), 0);
  const exceptional: readonly (readonly [string, number])[] = [['unknownShapes', counts.unknownShapes],
    ['cut', counts.cut + purposesCut], ['detailsUnavailable', counts.detailsUnavailable], ['dynamicTitles', counts.dynamicTitles],
    ['testsUnavailable', counts.testsUnavailable], ['unclassifiedExercises', unclassifiedExercises], ['coverage', counts.coverage]];
  for (const [key, value] of exceptional) if (value !== 0) meta[key] = value;
  return `${JSON.stringify(meta)}\n`;
}

/**
 * The complete architect view of `projection` at `revision`. Measured
 * dependency facts and test references must be those of the projection's
 * input; facts or references naming another `inputId`, or a record naming a
 * module the projection does not list, throw.
 */
export function renderArchitectView(input: {
  readonly revision: string;
  readonly projection: ArchitectViewProjection;
  readonly dependencies: ArchitectDependencies;
  readonly measurements: ArchitectMeasurements;
}): RenderedArchitectView {
  const { revision, projection, dependencies, measurements } = input;
  if (dependencies.state === 'measured' && dependencies.facts.inputId !== projection.inputId) {
    throw new Error(`Dependency facts for input ${dependencies.facts.inputId} cannot render the architect view of input ${projection.inputId}`);
  }
  const references = dependencies.state === 'measured' ? dependencies.testReferences : null;
  if (references && references.inputId !== projection.inputId) {
    throw new Error(`Test references for input ${references.inputId} cannot render the architect view of input ${projection.inputId}`);
  }
  const measuredByModule = measurements.state === 'measured'
    ? new Map(measurements.modules.map(module => [module.id, module])) : new Map<string, ModuleMeasurement>();
  if (measurements.state === 'measured' && (measuredByModule.size !== projection.modules.length
    || projection.modules.some(module => !measuredByModule.has(module.module)))) {
    throw new Error('Architect measurements do not name exactly the projection modules');
  }
  if (measurements.state === 'measured') for (const facts of projection.modules) {
    const module = measuredByModule.get(facts.module)!;
    if (module.dir !== facts.dir || module.parent !== facts.parent) {
      throw new Error(`Architect measurement identity does not match module ${facts.module}`);
    }
    const exactPresent = module.exact.views !== undefined;
    const subtreePresent = module.subtree.views !== undefined;
    if (exactPresent !== subtreePresent || (measurements.views === 'measured') !== exactPresent) {
      throw new Error('Architect view-byte availability is not uniform');
    }
  }
  const use = dependencies.state === 'measured' ? useOf(dependencies.facts) : null;
  const exercises = references ? exercisesOf(references, projection) : null;
  const records = new Map<ModuleId, { behavior: SymbolRecord[]; supporting: SymbolRecord[]; tests: ArchitectTestRecord[] }>(
    projection.modules.map(module => [module.module, { behavior: [], supporting: [], tests: [] }]));
  const of = (module: ModuleId) => {
    const found = records.get(module);
    if (!found) throw new Error(`The architect projection has a record for module "${module}", which it does not list`);
    return found;
  };
  for (const symbol of projection.symbols) {
    const record = symbolRecord(symbol, use ? use.consumers.get(identity(symbol.original)) ?? new Map() : null);
    of(symbol.module)[symbol.behavior === null ? 'supporting' : 'behavior'].push(record);
  }
  for (const test of projection.tests) of(test.module).tests.push(test);

  let purposesCut = 0;
  const summaries: ModuleSummary[] = projection.modules.map(facts => {
    const found = of(facts.module);
    const purpose = facts.purpose.state === 'present' ? cutUtf8(facts.purpose.text, bounds.purposeBytes) : null;
    if (purpose?.cut) purposesCut++;
    return {
      facts, purpose,
      behavior: found.behavior.sort(behaviorOrder),
      supporting: found.supporting.sort(supportingOrder),
      // By file, then source order: the sort is stable over the projection's source order.
      tests: found.tests.sort((a, b) => byteOrder(a.file, b.file)),
      uses: use ? pairs(use.uses.get(facts.module)) : null,
      usedBy: use ? pairs(use.usedBy.get(facts.module)) : null,
    };
  });

  const files: ArchitectViewFile[] = [
    { path: '_meta.json', text: metadata(revision, projection, dependencies, exercises, purposesCut, measurements) },
    { path: 'README.md', text: readme(revision, projection, summaries) },
  ];
  let recordCount = 0;
  for (const summary of summaries) {
    const directory = viewDirectory(summary.facts.module, projection.root);
    const at = (name: string): string => directory ? `${directory}/${name}` : name;
    files.push({ path: at('module.json'), text: moduleDocument(summary, revision, measurements, measuredByModule.get(summary.facts.module)) },
      { path: at('behavior.jsonl'), text: jsonl(summary.behavior.map(record => record.line)) },
      { path: at('supporting.jsonl'), text: jsonl(summary.supporting.map(record => record.line)) },
      { path: at('tests.jsonl'), text: jsonl(summary.tests.map(record => testRecord(record, exercises))) });
    recordCount += summary.behavior.length + summary.supporting.length + summary.tests.length;
  }
  files.sort((a, b) => byteOrder(a.path, b.path));
  return {
    files,
    modules: projection.modules.length,
    records: recordCount,
    bytes: files.reduce((total, file) => total + Buffer.byteLength(file.text, 'utf8'), 0),
    dependencies: dependencies.state,
  };
}

/** A module's view directory: its identifier without the root's identifier and the slash after it; `''` for the root. */
function viewDirectory(module: ModuleId, root: ModuleId): string {
  if (module === root) return '';
  if (!module.startsWith(`${root}/`)) throw new Error(`Module "${module}" is not beneath the root module "${root}"`);
  return module.slice(root.length + 1);
}
